name: A workflow for my WatchKart
on: push
jobs:
  build:
    name: Hello! WatchKart here
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "WatchKart"
